"""Agregar campo descripcion a articulos

Revision ID: dc3c768208ee
Revises: b375a017f8c3
Create Date: 2025-12-15 14:58:16.366344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3c768208ee'
down_revision = 'b375a017f8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
